# AUTO-GENERATED TESTS for infrastructure/persistence_orm/audit_event_table.py
# =========================================
# Regenerated by gen_tests.py (AST-based, real code)
# Source module: infrastructure.persistence_orm.audit_event_table
# Note: constructor/method smoke tests use mocked collaborators;
#       tests pytest.skip() with the real exception message when a
#       method genuinely needs live infra (DB/broker/etc).

from datetime import UTC, datetime
from unittest.mock import MagicMock
from uuid import uuid4

import pytest

from infrastructure.persistence_orm.audit_event_table import AuditEventTable


class TestAuditEventTable:
    """Tests for the AuditEventTable ORM table model."""

    def test_tablename_defined(self):
        """ORM model declares a table name."""
        assert hasattr(AuditEventTable, '__tablename__')
        assert isinstance(AuditEventTable.__tablename__, str)
        assert len(AuditEventTable.__tablename__) > 0

    def test_instantiation(self):
        """ORM model can be instantiated in-memory (without a DB session)."""
        kwargs = {
            'id': uuid4(),
            'event_type': "test_value",
            'severity': "test_value",
            'user_id': MagicMock(),
            'username': "test_value",
            'ip_address': "test_value",
            'user_agent': "test_value",
            'action': "test_value",
            'resource_type': "test_value",
            'resource_id': "test_value",
            'old_value': {},
            'new_value': {},
            'details': {},
            'error_message': "test_value",
            'timestamp': datetime.now(UTC),
            'correlation_id': "test_value",
            'request_id': "test_value",
            'aggregate_type': "test_value",
            'aggregate_id': MagicMock(),
            'legal_entity_id': MagicMock(),
        }
        try:
            instance = AuditEventTable(**kwargs)
        except (Exception, SystemExit) as e:
            pytest.skip(f"ORM instantiation needs a live session/mapper config: {e}")
            return
        assert isinstance(instance, AuditEventTable)
