# AUTO-GENERATED TESTS for infrastructure/persistence_orm/ap_invoice_line_table.py
# =========================================
# Regenerated by gen_tests.py (AST-based, real code)
# Source module: infrastructure.persistence_orm.ap_invoice_line_table
# Note: constructor/method smoke tests use mocked collaborators;
#       tests pytest.skip() with the real exception message when a
#       method genuinely needs live infra (DB/broker/etc).

from decimal import Decimal
from unittest.mock import MagicMock

import pytest

from infrastructure.persistence_orm.ap_invoice_line_table import APInvoiceLineTable


class TestAPInvoiceLineTable:
    """Tests for the APInvoiceLineTable ORM table model."""

    def test_tablename_defined(self):
        """ORM model declares a table name."""
        assert hasattr(APInvoiceLineTable, '__tablename__')
        assert isinstance(APInvoiceLineTable.__tablename__, str)
        assert len(APInvoiceLineTable.__tablename__) > 0

    def test_instantiation(self):
        """ORM model can be instantiated in-memory (without a DB session)."""
        kwargs = dict(
            id=MagicMock(),
            invoice_id=MagicMock(),
            line_number=1,
            description="test_value",
            account_code="test_value",
            quantity=Decimal("100.00"),
            unit_price=Decimal("100.00"),
            amount=Decimal("100.00"),
            tax_rate=Decimal("100.00"),
            tax_amount=Decimal("100.00"),
            total_amount=Decimal("100.00"),
            cost_center="test_value",
            project_id=MagicMock(),
            invoice=MagicMock(),
        )
        try:
            instance = APInvoiceLineTable(**kwargs)
        except (Exception, SystemExit) as e:
            pytest.skip(f"ORM instantiation needs a live session/mapper config: {e}")
            return
        assert isinstance(instance, APInvoiceLineTable)
