# AUTO-GENERATED TESTS for infrastructure/persistence_orm/report_definition_table.py
# =========================================
# Regenerated by gen_tests.py (AST-based, real code)
# Source module: infrastructure.persistence_orm.report_definition_table
# Note: constructor/method smoke tests use mocked collaborators;
#       tests pytest.skip() with the real exception message when a
#       method genuinely needs live infra (DB/broker/etc).

from unittest.mock import MagicMock
from uuid import uuid4

import pytest

from infrastructure.persistence_orm.report_definition_table import ReportDefinitionTable


class TestReportDefinitionTable:
    """Tests for the ReportDefinitionTable ORM table model."""

    def test_tablename_defined(self):
        """ORM model declares a table name."""
        assert hasattr(ReportDefinitionTable, '__tablename__')
        assert isinstance(ReportDefinitionTable.__tablename__, str)
        assert len(ReportDefinitionTable.__tablename__) > 0

    def test_instantiation(self):
        """ORM model can be instantiated in-memory (without a DB session)."""
        kwargs = dict(
            id=uuid4(),
            report_code="test_value",
            report_name="test_value",
            description="test_value",
            category="test_value",
            query_sql="test_value",
            parameters_schema={},
            template_path="test_value",
            output_formats=["test_value"],
            is_active=True,
            created_by=MagicMock(),
        )
        try:
            instance = ReportDefinitionTable(**kwargs)
        except (Exception, SystemExit) as e:
            pytest.skip(f"ORM instantiation needs a live session/mapper config: {e}")
            return
        assert isinstance(instance, ReportDefinitionTable)
