# AUTO-GENERATED TESTS for infrastructure/persistence_orm/saga_state_table.py
# =========================================
# Regenerated by gen_tests.py (AST-based, real code)
# Source module: infrastructure.persistence_orm.saga_state_table
# Note: constructor/method smoke tests use mocked collaborators;
#       tests pytest.skip() with the real exception message when a
#       method genuinely needs live infra (DB/broker/etc).

from datetime import UTC, datetime
from unittest.mock import MagicMock
from uuid import uuid4

import pytest

from infrastructure.persistence_orm.saga_state_table import SagaStateTable


class TestSagaStateTable:
    """Tests for the SagaStateTable ORM table model."""

    def test_tablename_defined(self):
        """ORM model declares a table name."""
        assert hasattr(SagaStateTable, '__tablename__')
        assert isinstance(SagaStateTable.__tablename__, str)
        assert len(SagaStateTable.__tablename__) > 0

    def test_instantiation(self):
        """ORM model can be instantiated in-memory (without a DB session)."""
        kwargs = dict(
            id=uuid4(),
            saga_id=uuid4(),
            saga_type="test_value",
            correlation_id="test_value",
            state_data={},
            current_step=1,
            total_steps=1,
            step_history=[MagicMock()],
            status="test_value",
            error_message="test_value",
            retry_count=1,
            max_retries=1,
            next_retry_at=datetime.now(UTC),
            started_at=datetime.now(UTC),
            completed_at=datetime.now(UTC),
            timeout_seconds=1,
            legal_entity_id=MagicMock(),
            created_by=MagicMock(),
        )
        try:
            instance = SagaStateTable(**kwargs)
        except (Exception, SystemExit) as e:
            pytest.skip(f"ORM instantiation needs a live session/mapper config: {e}")
            return
        assert isinstance(instance, SagaStateTable)
