# AUTO-GENERATED TESTS for infrastructure/persistence_orm/tax_transaction_table.py
# =========================================
# Regenerated by gen_tests.py (AST-based, real code)
# Source module: infrastructure.persistence_orm.tax_transaction_table
# Note: constructor/method smoke tests use mocked collaborators;
#       tests pytest.skip() with the real exception message when a
#       method genuinely needs live infra (DB/broker/etc).

from datetime import date
from decimal import Decimal
from unittest.mock import MagicMock

import pytest

from infrastructure.persistence_orm.tax_transaction_table import TaxTransactionTable


class TestTaxTransactionTable:
    """Tests for the TaxTransactionTable ORM table model."""

    def test_tablename_defined(self):
        """ORM model declares a table name."""
        assert hasattr(TaxTransactionTable, '__tablename__')
        assert isinstance(TaxTransactionTable.__tablename__, str)
        assert len(TaxTransactionTable.__tablename__) > 0

    def test_instantiation(self):
        """ORM model can be instantiated in-memory (without a DB session)."""
        kwargs = dict(
            transaction_number="test_value",
            transaction_date=date.today(),
            tax_type="test_value",
            tax_period_type="test_value",
            tax_period_year=1,
            tax_period_month=1,
            taxable_amount=Decimal("100.00"),
            tax_rate=Decimal("100.00"),
            tax_amount=Decimal("100.00"),
            currency="test_value",
            is_withholding=True,
            counterparty_tax_id="test_value",
            counterparty_name="test_value",
            ntpn="test_value",
            payment_date=date.today(),
            reference_type="test_value",
            reference_id=MagicMock(),
            spt_number="test_value",
            filing_date=date.today(),
            status="test_value",
            extra_metadata={},
            created_by=MagicMock(),
        )
        try:
            instance = TaxTransactionTable(**kwargs)
        except (Exception, SystemExit) as e:
            pytest.skip(f"ORM instantiation needs a live session/mapper config: {e}")
            return
        assert isinstance(instance, TaxTransactionTable)
