"""
Package: application.dto_objects

Data Transfer Objects untuk seluruh aplikasi ERP.
Mendukung serialisasi/deserialisasi JSON, validasi, dan konversi domain-DTO.
"""

from __future__ import annotations

# Account DTOs
from application.dto_objects.account_dto import (
    AccountHierarchyNodeDTO,
    AccountResponse,
    AccountStatusDTO,
    AccountTypeDTO,
    BulkImportResultDTO,
    CreateAccountRequest,
    UpdateAccountRequest,
)

# AP (Accounts Payable) DTOs
from application.dto_objects.ap_invoice_request import (
    APCreditNoteCreateRequest,
    APCreditNoteReason,
    APInvoiceCreateRequest,
    APInvoiceLineRequest,
    ApInvoiceRequest,
    APInvoiceRequestDTO,
    APInvoiceRequestFactory,
    APInvoiceStatus,
    APInvoiceType,
    APPaymentCreateRequest,
    APPaymentMethod,
    APPaymentRunRequest,
    APPaymentRunRequestDTO,
    APPaymentStatus,
    ApproveAPInvoiceRequest,
    CreateAPCreditNoteRequest,
    CreateAPInvoiceRequest,
    GetAPAgingRequest,
    GetAPInvoiceRequest,
    ListAPInvoicesRequest,
    RecordAPPaymentRequest,
    ThreeWayMatchRequestDTO,
    UpdateAPInvoiceRequest,
    VerifyAPInvoiceRequest,
    WithholdingArticle,
)

# AP Response DTOs
from application.dto_objects.ap_response import (
    APAgingBucketDTO,
    APAgingReportDTO,
    APCreditNoteResponseDTO,
    APInvoiceResponseDTO,
    APPaymentResponseDTO,
    APPaymentRunResponseDTO,
    APVendorBalanceDTO,
    ThreeWayMatchResultDTO,
)

# AR (Accounts Receivable) DTOs
from application.dto_objects.ar_invoice_request import (
    ARCreditNoteCreateRequest,
    ARInvoiceCreateRequest,
    ARInvoiceLineRequest,
    ARInvoiceRequestDTO,
    ARInvoiceRequestFactory,
    ARInvoiceStatus,
    ARInvoiceType,
    ARPaymentCreateRequest,
    CreateARCreditNoteRequest,
    CreateARInvoiceRequest,
    CreditNoteReason,
    GetARAgingRequest,
    GetARInvoiceRequest,
    ListARInvoicesRequest,
    PaymentMethod,
    PaymentStatus,
    RecordARPaymentRequest,
    UpdateARInvoiceRequest,
    WriteOffARInvoiceRequest,
)

# Bank & Cash DTOs
from application.dto_objects.bank_cash_request import (
    BankAccountRequest,
    BankAccountUpdateRequest,
    BankChargeRequest,
    BankDepositRequest,
    BankReconciliationCompleteRequest,
    BankReconciliationRequestDTO,
    BankReconciliationStartRequest,
    BankTransferRequest,
    BankWithdrawalRequest,
    CashTransactionRequest,
    CompleteReconciliationRequest,
    CreateBankAccountRequest,
    CreateCashBookRequest,
    DepositRequest,
    GetBankAccountBalanceRequest,
    GetBankAccountRequest,
    GetCashBalanceRequest,
    GetReconciliationStatusRequest,
    InterestRequest,
    ListBankAccountsRequest,
    ListBankTransactionsRequest,
    PettyCashReplenishRequest,
    StartReconciliationRequest,
    TransferRequest,
    UpdateBankAccountRequest,
    WithdrawalRequest,
)

# COA (Chart of Accounts) DTOs
from application.dto_objects.coa_request import (
    AccountCreateRequest,
    AccountQueryParams,
    AccountUpdateRequest,
    GetAccountsQuery,
)
from application.dto_objects.coa_request import (
    CreateAccountRequest as COACreateAccountRequest,
)
from application.dto_objects.coa_request import (
    UpdateAccountRequest as COAUpdateAccountRequest,
)

# Coretax DJP DTOs
from application.dto_objects.coretax_submission_request import (
    NPWP,
    NTPN,
    BuktiPotongPPh23DTO,
    CoretaxAuthRequest,
    CoretaxDTOValidationError,
    CoretaxDTOValidator,
    CoretaxQueryRequest,
    CoretaxRetrievalRequest,
    CoretaxSerializationError,
    CoretaxSubmissionRequest,
    CoretaxSubmissionResponse,
    FakturPajakKeluaranDTO,
    FakturPajakKode,
    FakturPajakMasukanDTO,
    JenisLaporan,
    JenisPajak,
    KodeObjekPajak,
    LampiranSPTPPN,
    MasaPajak,
    NTPNReference,
    SPTMasaPph21Request,
    SPTMasaPph23Request,
    SPTMasaPpnRequest,
    SPTTahunanBadanRequest,
    StatusCoretaxSubmission,
    TahunPajak,
    deserialize_coretax_response,
    serialize_coretax_request,
)

# Financial Statement DTOs
from application.dto_objects.financial_statement_request import (
    AccountFilter,
    BalanceSheetDTO,
    BalanceSheetRequest,
    CashFlowDTO,
    CashFlowMethod,
    CashFlowStatementRequest,
    ComparativePeriod,
    ComparativeType,
    CurrencyType,
    DateRange,
    EquityStatementRequest,
    FinancialStatementRequestDTO,
    FinancialStatementRequestFactory,
    FinancialStatementResult,
    FinancialStatementType,
    GeneralLedgerRequest,
    IncomeStatementDTO,
    IncomeStatementRequest,
    OutputFormat,
    SubsidiaryLedgerRequest,
    TrialBalanceDTO,
    TrialBalanceRequest,
)

# Fixed Asset DTOs
from application.dto_objects.fixed_asset_request import (
    AssetCreateRequest,
    AssetUpdateRequest,
    CreateFixedAssetRequest,
    DepreciationRunRequest,
    DisposalRequest,
    FixedAssetDepreciationRequest,
    FixedAssetDisposalRequest,
    GetFixedAssetsQuery,
    ImpairmentTestRequest,
    RevaluationRequest,
    UpdateFixedAssetRequest,
)

# Forex DTOs
from application.dto_objects.forex_request import (
    ForexRateRequest,
    ForexRevaluationRequest,
)

# Intangible Asset DTOs
from application.dto_objects.intangible_asset_request import (
    AmortizeRequest,
    CreateIntangibleAssetRequest,
    DisposeAssetRequest,
)
from application.dto_objects.intangible_asset_request import (
    ImpairmentTestRequest as IntangibleImpairmentTestRequest,
)

# Inventory DTOs
from application.dto_objects.inventory_request import (
    COGSCalculationRequest,
    COGSCalculationRequestDTO,
    CreateItemRequestDTO,
    InterWarehouseTransferRequest,
    InventoryValuationRequest,
    InventoryValuationRequestDTO,
    ItemCreateRequest,
    ItemUpdateRequest,
    LowStockAlertQuery,
    LowStockAlertQueryDTO,
    StockMovementRequest,
    StockMovementRequestDTO,
    StockOpnameRequest,
    StockOpnameRequestDTO,
    TransferRequestDTO,
    UpdateItemRequestDTO,
)

# Inventory Response DTOs
from application.dto_objects.inventory_response import (
    InventorySummaryDTO,
    ItemResponseDTO,
    StockCardResponseDTO,
    StockMovementResponseDTO,
    StockOpnameResponseDTO,
    TransferResponseDTO,
    ValuationReportDTO,
)

# Journal DTOs
from application.dto_objects.journal_request import (
    VALID_JOURNAL_TYPES,
    VALID_SIDES,
    AdjustingJournalRequestDTO,
    ApproveJournalRequest,
    CreateJournalEntryRequest,
    CreateJournalRequest,
    GetJournalRequest,
    JournalCreateRequest,
    JournalEntryRequest,
    JournalEntryRequestDTO,
    JournalEntryStatusDTO,
    JournalLineRequest,
    JournalLineRequestDTO,
    JournalQueryParams,
    JournalRequest,
    JournalRequestFactory,
    JournalResponseDTO,
    JournalUpdateRequest,
    ListJournalsRequest,
    PostJournalRequest,
    RecurringJournalTemplateDTO,
    RejectJournalRequest,
    ReverseJournalRequest,
    SubmitJournalRequest,
    UpdateJournalRequest,
)

# Journal Response DTOs
from application.dto_objects.journal_response import (
    JournalEntryResponseDTO,
    JournalLine,
    JournalLineResponseDTO,
    JournalResponse,
    JournalValidationResult,
    JournalValidationResultDTO,
)

# Manufacturing DTOs
from application.dto_objects.manufacturing_request import (
    GetWorkOrderRequest,
    LaborRecordDTO,
    LaborRecordRequest,
    ListWorkOrdersRequest,
    ManufacturingCostSummaryRequest,
    ManufacturingOrderType,
    ManufacturingRequestFactory,
    MaterialIssueDTO,
    MaterialIssueRequest,
    ProductionCompletionDTO,
    ProductionCompletionRequest,
    UpdateWorkOrderRequest,
    WorkOrderCreateRequest,
    WorkOrderRequest,
    WorkOrderStatus,
)

# Payment Run DTOs
from application.dto_objects.payment_run_request import (
    ApprovePaymentRunRequest,
    CancelPaymentRunRequest,
    CreatePaymentRunRequest,
    GetPaymentRunRequest,
    InvoiceSelectionCriteria,
    ListPaymentRunsRequest,
    PaymentInstruction,
    PaymentPriority,
    PaymentRunRequestDTO,
    PaymentRunRequestFactory,
    PaymentRunResponseDTO,
    PaymentRunSchedule,
    PaymentRunStatus,
    PaymentRunStatusDTO,
    PaymentRunSummaryRequest,
    PaymentRunType,
    PaymentSelectionMethod,
    ProcessPaymentRunRequest,
    RejectPaymentRunRequest,
    UpdatePaymentRunRequest,
)

# Period Close DTOs
from application.dto_objects.period_close_request import (
    ArchivePeriodRequest,
    CloseAction,
    ClosePeriodRequest,
    GetCurrentPeriodRequest,
    GetPeriodByDateRequest,
    GetPeriodRequest,
    ListPeriodsRequest,
    LockPeriodRequest,
    PeriodCloseRequestDTO,
    PeriodCloseRequestFactory,
    PeriodCloseResponseDTO,
    PeriodCloseStatusDTO,
    PeriodCloseSummary,
    PeriodInfo,
    PeriodLockRequestDTO,
    PeriodReadinessReport,
    PeriodReopenRequestDTO,
    PeriodStatus,
    PeriodType,
    ReopenPeriodRequest,
    ReopenReason,
    VerifyPeriodReadinessRequest,
)

__version__ = "2.0.0"

__all__ = [
    "NPWP",
    "NTPN",
    "VALID_JOURNAL_TYPES",
    "VALID_SIDES",
    # AP Response
    "APAgingBucketDTO",
    "APAgingReportDTO",
    # AP Request
    "APCreditNoteCreateRequest",
    "APCreditNoteReason",
    "APCreditNoteResponseDTO",
    "APInvoiceCreateRequest",
    "APInvoiceLineRequest",
    "APInvoiceRequestDTO",
    "APInvoiceRequestFactory",
    "APInvoiceResponseDTO",
    "APInvoiceStatus",
    "APInvoiceType",
    "APPaymentCreateRequest",
    "APPaymentMethod",
    "APPaymentResponseDTO",
    "APPaymentRunRequest",
    "APPaymentRunRequestDTO",
    "APPaymentRunResponseDTO",
    "APPaymentStatus",
    "APVendorBalanceDTO",
    # AR Request
    "ARCreditNoteCreateRequest",
    "ARInvoiceCreateRequest",
    "ARInvoiceLineRequest",
    "ARInvoiceRequestDTO",
    "ARInvoiceRequestFactory",
    "ARInvoiceStatus",
    "ARInvoiceType",
    "ARPaymentCreateRequest",
    # COA
    "AccountCreateRequest",
    # Financial Statement
    "AccountFilter",
    # Account
    "AccountHierarchyNodeDTO",
    "AccountQueryParams",
    "AccountResponse",
    "AccountStatusDTO",
    "AccountTypeDTO",
    "AccountUpdateRequest",
    # Journal Request
    "AdjustingJournalRequestDTO",
    # Intangible Asset
    "AmortizeRequest",
    "ApInvoiceRequest",
    "ApproveAPInvoiceRequest",
    "ApproveJournalRequest",
    # Payment Run
    "ApprovePaymentRunRequest",
    # Period Close
    "ArchivePeriodRequest",
    # Fixed Asset
    "AssetCreateRequest",
    "AssetUpdateRequest",
    "BalanceSheetDTO",
    "BalanceSheetRequest",
    # Bank & Cash
    "BankAccountRequest",
    "BankAccountUpdateRequest",
    "BankChargeRequest",
    "BankDepositRequest",
    "BankReconciliationCompleteRequest",
    "BankReconciliationRequestDTO",
    "BankReconciliationStartRequest",
    "BankTransferRequest",
    "BankWithdrawalRequest",
    # Coretax
    "BuktiPotongPPh23DTO",
    "BulkImportResultDTO",
    "COACreateAccountRequest",
    "COAUpdateAccountRequest",
    # Inventory Request
    "COGSCalculationRequest",
    "COGSCalculationRequestDTO",
    "CancelPaymentRunRequest",
    "CashFlowDTO",
    "CashFlowMethod",
    "CashFlowStatementRequest",
    "CashTransactionRequest",
    "CloseAction",
    "ClosePeriodRequest",
    "ComparativePeriod",
    "ComparativeType",
    "CompleteReconciliationRequest",
    "CoretaxAuthRequest",
    "CoretaxDTOValidationError",
    "CoretaxDTOValidator",
    "CoretaxQueryRequest",
    "CoretaxRetrievalRequest",
    "CoretaxSerializationError",
    "CoretaxSubmissionRequest",
    "CoretaxSubmissionResponse",
    "CreateAPCreditNoteRequest",
    "CreateAPInvoiceRequest",
    "CreateARCreditNoteRequest",
    "CreateARInvoiceRequest",
    "CreateAccountRequest",
    "CreateBankAccountRequest",
    "CreateCashBookRequest",
    "CreateFixedAssetRequest",
    "CreateIntangibleAssetRequest",
    "CreateItemRequestDTO",
    "CreateJournalEntryRequest",
    "CreateJournalRequest",
    "CreatePaymentRunRequest",
    "CreditNoteReason",
    "CurrencyType",
    "DateRange",
    "DepositRequest",
    "DepreciationRunRequest",
    "DisposalRequest",
    "DisposeAssetRequest",
    "EquityStatementRequest",
    "FakturPajakKeluaranDTO",
    "FakturPajakKode",
    "FakturPajakMasukanDTO",
    "FinancialStatementRequestDTO",
    "FinancialStatementRequestFactory",
    "FinancialStatementResult",
    "FinancialStatementType",
    "FixedAssetDepreciationRequest",
    "FixedAssetDisposalRequest",
    # Forex
    "ForexRateRequest",
    "ForexRevaluationRequest",
    "GeneralLedgerRequest",
    "GetAPAgingRequest",
    "GetAPInvoiceRequest",
    "GetARAgingRequest",
    "GetARInvoiceRequest",
    "GetAccountsQuery",
    "GetBankAccountBalanceRequest",
    "GetBankAccountRequest",
    "GetCashBalanceRequest",
    "GetCurrentPeriodRequest",
    "GetFixedAssetsQuery",
    "GetJournalRequest",
    "GetPaymentRunRequest",
    "GetPeriodByDateRequest",
    "GetPeriodRequest",
    "GetReconciliationStatusRequest",
    # Manufacturing
    "GetWorkOrderRequest",
    "ImpairmentTestRequest",
    "IncomeStatementDTO",
    "IncomeStatementRequest",
    "IntangibleImpairmentTestRequest",
    "InterWarehouseTransferRequest",
    "InterestRequest",
    # Inventory Response
    "InventorySummaryDTO",
    "InventoryValuationRequest",
    "InventoryValuationRequestDTO",
    "InvoiceSelectionCriteria",
    "ItemCreateRequest",
    "ItemResponseDTO",
    "ItemUpdateRequest",
    "JenisLaporan",
    "JenisPajak",
    "JournalCreateRequest",
    "JournalEntryRequest",
    "JournalEntryRequestDTO",
    # Journal Response
    "JournalEntryResponseDTO",
    "JournalEntryStatusDTO",
    "JournalLine",
    "JournalLineRequest",
    "JournalLineRequestDTO",
    "JournalLineResponseDTO",
    "JournalQueryParams",
    "JournalRequest",
    "JournalRequestFactory",
    "JournalResponse",
    "JournalResponseDTO",
    "JournalUpdateRequest",
    "JournalValidationResult",
    "JournalValidationResultDTO",
    "KodeObjekPajak",
    "LaborRecordDTO",
    "LaborRecordRequest",
    "LampiranSPTPPN",
    "ListAPInvoicesRequest",
    "ListARInvoicesRequest",
    "ListBankAccountsRequest",
    "ListBankTransactionsRequest",
    "ListJournalsRequest",
    "ListPaymentRunsRequest",
    "ListPeriodsRequest",
    "ListWorkOrdersRequest",
    "LockPeriodRequest",
    "LowStockAlertQuery",
    "LowStockAlertQueryDTO",
    "ManufacturingCostSummaryRequest",
    "ManufacturingOrderType",
    "ManufacturingRequestFactory",
    "MasaPajak",
    "MaterialIssueDTO",
    "MaterialIssueRequest",
    "NTPNReference",
    "OutputFormat",
    "PaymentInstruction",
    "PaymentMethod",
    "PaymentPriority",
    "PaymentRunRequestDTO",
    "PaymentRunRequestFactory",
    "PaymentRunResponseDTO",
    "PaymentRunSchedule",
    "PaymentRunStatus",
    "PaymentRunStatusDTO",
    "PaymentRunSummaryRequest",
    "PaymentRunType",
    "PaymentSelectionMethod",
    "PaymentStatus",
    "PeriodCloseRequestDTO",
    "PeriodCloseRequestFactory",
    "PeriodCloseResponseDTO",
    "PeriodCloseStatusDTO",
    "PeriodCloseSummary",
    "PeriodInfo",
    "PeriodLockRequestDTO",
    "PeriodReadinessReport",
    "PeriodReopenRequestDTO",
    "PeriodStatus",
    "PeriodType",
    "PettyCashReplenishRequest",
    "PostJournalRequest",
    "ProcessPaymentRunRequest",
    "ProductionCompletionDTO",
    "ProductionCompletionRequest",
    "RecordAPPaymentRequest",
    "RecordARPaymentRequest",
    "RecurringJournalTemplateDTO",
    "RejectJournalRequest",
    "RejectPaymentRunRequest",
    "ReopenPeriodRequest",
    "ReopenReason",
    "RevaluationRequest",
    "ReverseJournalRequest",
    "SPTMasaPph21Request",
    "SPTMasaPph23Request",
    "SPTMasaPpnRequest",
    "SPTTahunanBadanRequest",
    "StartReconciliationRequest",
    "StatusCoretaxSubmission",
    "StockCardResponseDTO",
    "StockMovementRequest",
    "StockMovementRequestDTO",
    "StockMovementResponseDTO",
    "StockOpnameRequest",
    "StockOpnameRequestDTO",
    "StockOpnameResponseDTO",
    "SubmitJournalRequest",
    "SubsidiaryLedgerRequest",
    "TahunPajak",
    "ThreeWayMatchRequestDTO",
    "ThreeWayMatchResultDTO",
    "TransferRequest",
    "TransferRequestDTO",
    "TransferResponseDTO",
    "TrialBalanceDTO",
    "TrialBalanceRequest",
    "UpdateAPInvoiceRequest",
    "UpdateARInvoiceRequest",
    "UpdateAccountRequest",
    "UpdateBankAccountRequest",
    "UpdateFixedAssetRequest",
    "UpdateItemRequestDTO",
    "UpdateJournalRequest",
    "UpdatePaymentRunRequest",
    "UpdateWorkOrderRequest",
    "ValuationReportDTO",
    "VerifyAPInvoiceRequest",
    "VerifyPeriodReadinessRequest",
    "WithdrawalRequest",
    "WithholdingArticle",
    "WorkOrderCreateRequest",
    "WorkOrderRequest",
    "WorkOrderStatus",
    "WriteOffARInvoiceRequest",
    # Version
    "__version__",
    "deserialize_coretax_response",
    "serialize_coretax_request",
]
