"""resolve_final_schema_drift

Revision ID: f713e2633e6a
Revises: f4aee3b9db2a
Create Date: 2026-08-10 15:41:32.063927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f713e2633e6a'
down_revision: Union[str, None] = 'f4aee3b9db2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('goods_receipt_line', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default='now()',
               existing_nullable=True)
    op.alter_column('goods_receipt_line', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default='now()',
               existing_nullable=True)
    op.create_index('idx_cost_card_product', 'manufacturing_cost_card', ['product_id'], unique=False, if_not_exists=True)
    op.alter_column('payroll_adjustment', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default='now()',
               existing_nullable=True)
    op.alter_column('payroll_adjustment', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default='now()',
               existing_nullable=True)
    op.alter_column('payroll_detail', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default='now()',
               existing_nullable=True)
    op.alter_column('payroll_detail', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default='now()',
               existing_nullable=True)
    op.alter_column('pph_withholding_summary', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default='now()',
               existing_nullable=True)
    op.alter_column('pph_withholding_summary', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default='now()',
               existing_nullable=True)
    op.alter_column('ppn_settlement', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default='now()',
               existing_nullable=True)
    op.alter_column('ppn_settlement', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default='now()',
               existing_nullable=True)
    op.alter_column('saga_event', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default='now()',
               existing_nullable=True)
    op.alter_column('saga_instance', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default='now()',
               existing_nullable=True)
    op.alter_column('saga_instance', 'last_heartbeat_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default='now()',
               existing_nullable=True)
    op.alter_column('saga_lock', 'locked_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default='now()',
               existing_nullable=True)
    op.alter_column('saga_step_log', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default='now()',
               existing_nullable=True)
    op.alter_column('salary_structure', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default='now()',
               existing_nullable=True)
    op.alter_column('salary_structure', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default='now()',
               existing_nullable=True)
    op.alter_column('sales_order_line', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default='now()',
               existing_nullable=True)
    op.alter_column('sales_order_line', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default='now()',
               existing_nullable=True)
    op.alter_column('umkm_journal', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default='now()',
               existing_nullable=True)
    op.alter_column('umkm_journal', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default='now()',
               existing_nullable=True)
    op.alter_column('work_in_process', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default='now()',
               existing_nullable=True)
    op.alter_column('work_in_process', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default='now()',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('work_in_process', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text("'2026-08-10 15:40:14.77177'::timestamp without time zone"),
               existing_nullable=True)
    op.alter_column('work_in_process', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text("'2026-08-10 15:40:14.77177'::timestamp without time zone"),
               existing_nullable=True)
    op.alter_column('umkm_journal', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text("'2026-08-10 15:40:14.77177'::timestamp without time zone"),
               existing_nullable=True)
    op.alter_column('umkm_journal', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text("'2026-08-10 15:40:14.77177'::timestamp without time zone"),
               existing_nullable=True)
    op.alter_column('sales_order_line', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text("'2026-08-10 15:40:14.77177'::timestamp without time zone"),
               existing_nullable=True)
    op.alter_column('sales_order_line', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text("'2026-08-10 15:40:14.77177'::timestamp without time zone"),
               existing_nullable=True)
    op.alter_column('salary_structure', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text("'2026-08-10 15:40:14.77177'::timestamp without time zone"),
               existing_nullable=True)
    op.alter_column('salary_structure', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text("'2026-08-10 15:40:14.77177'::timestamp without time zone"),
               existing_nullable=True)
    op.alter_column('saga_step_log', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text("'2026-08-10 15:40:14.77177'::timestamp without time zone"),
               existing_nullable=True)
    op.alter_column('saga_lock', 'locked_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text("'2026-08-10 15:40:14.77177'::timestamp without time zone"),
               existing_nullable=True)
    op.alter_column('saga_instance', 'last_heartbeat_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text("'2026-08-10 15:40:14.77177'::timestamp without time zone"),
               existing_nullable=True)
    op.alter_column('saga_instance', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text("'2026-08-10 15:40:14.77177'::timestamp without time zone"),
               existing_nullable=True)
    op.alter_column('saga_event', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text("'2026-08-10 15:40:14.77177'::timestamp without time zone"),
               existing_nullable=True)
    op.alter_column('ppn_settlement', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text("'2026-08-10 15:40:14.77177'::timestamp without time zone"),
               existing_nullable=True)
    op.alter_column('ppn_settlement', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text("'2026-08-10 15:40:14.77177'::timestamp without time zone"),
               existing_nullable=True)
    op.alter_column('pph_withholding_summary', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text("'2026-08-10 15:40:14.77177'::timestamp without time zone"),
               existing_nullable=True)
    op.alter_column('pph_withholding_summary', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text("'2026-08-10 15:40:14.77177'::timestamp without time zone"),
               existing_nullable=True)
    op.alter_column('payroll_detail', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text("'2026-08-10 15:40:14.77177'::timestamp without time zone"),
               existing_nullable=True)
    op.alter_column('payroll_detail', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text("'2026-08-10 15:40:14.77177'::timestamp without time zone"),
               existing_nullable=True)
    op.alter_column('payroll_adjustment', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text("'2026-08-10 15:40:14.77177'::timestamp without time zone"),
               existing_nullable=True)
    op.alter_column('payroll_adjustment', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text("'2026-08-10 15:40:14.77177'::timestamp without time zone"),
               existing_nullable=True)
    op.drop_index('idx_cost_card_product', table_name='manufacturing_cost_card')
    op.alter_column('goods_receipt_line', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text("'2026-08-10 15:40:14.77177'::timestamp without time zone"),
               existing_nullable=True)
    op.alter_column('goods_receipt_line', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text("'2026-08-10 15:40:14.77177'::timestamp without time zone"),
               existing_nullable=True)
    # ### end Alembic commands ###
