#!/usr/bin/env python3
"""
Module: outbox_relay_metrics_table.py
Layer: Infrastructure (Persistence ORM)
Responsibility: ORM table definition for 'outbox_relay_metrics'.
Auto-generated by P42 sync fix.
"""
from __future__ import annotations

from datetime import datetime
from decimal import Decimal
from uuid import UUID

from sqlalchemy import (
    DateTime,
    Integer,
    Numeric,
    String,
)
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlalchemy.orm import Mapped, mapped_column
from sqlalchemy.sql import text

from infrastructure.persistence_orm.base_model import Base


class OutboxRelayMetricsTable(Base):
    """ORM model for table: outbox_relay_metrics."""

    __tablename__ = "outbox_relay_metrics"

    id: Mapped[UUID] = mapped_column(PG_UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()"))
    consumer_group: Mapped[str] = mapped_column(String(255), nullable=False)
    poll_interval_ms: Mapped[int | None] = mapped_column(Integer(), nullable=True)
    batch_size: Mapped[int | None] = mapped_column(Integer(), nullable=True)
    processing_latency_avg_ms: Mapped[int | None] = mapped_column(Integer(), nullable=True)
    events_per_second: Mapped[Decimal | None] = mapped_column(Numeric(20, 6), nullable=True)
    queue_depth: Mapped[int | None] = mapped_column(Integer(), nullable=True)
    last_poll_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)

    def __repr__(self) -> str:
        pk = getattr(self, "id", "?")
        return f"<OutboxRelayMetricsTable id={pk}>"
