# AUTO-GENERATED TESTS for adapters/primary_api/v1/fastapi_iam_router.py
# =========================================
# Regenerated by gen_tests.py (AST-based, real code)
# Source module: adapters.primary_api.v1.fastapi_iam_router
# Note: constructor/method smoke tests use mocked collaborators;
#       tests pytest.skip() with the real exception message when a
#       method genuinely needs live infra (DB/broker/etc).

from datetime import UTC, datetime
from unittest.mock import MagicMock
from uuid import uuid4

import pytest

from adapters.primary_api.v1.fastapi_iam_router import (
    ChangePasswordSchema,
    ForgotPasswordResponseSchema,
    IdempotencyManager,
    LoginAttemptResponseSchema,
    LoginRequestSchema,
    LoginResponseSchema,
    MFADisableSchema,
    MFASetupResponseSchema,
    MFAType,
    MFAVerifySchema,
    PermissionResponseSchema,
    RefreshTokenRequestSchema,
    ResetPasswordConfirmSchema,
    ResetPasswordRequestSchema,
    RoleCreateSchema,
    RolePermissionAssignSchema,
    RoleResponseSchema,
    RoleStatus,
    RoleUpdateSchema,
    SessionResponseSchema,
    SessionStatus,
    UserAuditLogSchema,
    UserCreateSchema,
    UserResponseSchema,
    UserRoleAssignSchema,
    UserStatus,
    UserUpdateSchema,
    activate_user,
    assign_permissions_to_role,
    assign_roles_to_user,
    change_password,
    create_role,
    create_user,
    deactivate_user,
    delete_role,
    disable_mfa,
    forgot_password,
    get_iam_service,
    get_login_attempts,
    get_role,
    get_role_permissions,
    get_user,
    get_user_audit_log,
    get_user_by_username,
    get_user_history,
    get_user_roles,
    get_user_sessions,
    get_user_status,
    health,
    info,
    list_permissions,
    list_roles,
    list_users,
    lock_user,
    login,
    logout,
    ping,
    refresh_token,
    remove_permission_from_role,
    remove_role_from_user,
    reset_password,
    revoke_all_other_sessions,
    revoke_session,
    setup_mfa,
    unlock_user,
    update_role,
    update_user,
    verify_mfa,
)


class TestIdempotencyManager:
    def test_construction(self):
        instance = IdempotencyManager()
        assert isinstance(instance, IdempotencyManager)

    def test_get_cached_result_returns_none_for_missing_key(self):
        instance = IdempotencyManager()
        result = instance.get_cached_result("non_existent_key", "method")
        assert result is None

    def test_cache_result_returns_true_on_success(self):
        instance = IdempotencyManager()
        result = instance.cache_result("key", "method", {"data": "value"})
        assert result is True


class TestUserStatus:
    def test_members_exist(self):
        assert hasattr(UserStatus, 'ACTIVE')
        assert hasattr(UserStatus, 'INACTIVE')
        assert hasattr(UserStatus, 'LOCKED')
        assert hasattr(UserStatus, 'SUSPENDED')
        assert hasattr(UserStatus, 'PENDING_ACTIVATION')
        assert hasattr(UserStatus, 'PASSWORD_EXPIRED')
        assert hasattr(UserStatus, 'DELETED')

    def test_member_is_instance(self):
        assert isinstance(UserStatus.ACTIVE, UserStatus)


class TestRoleStatus:
    def test_members_exist(self):
        assert hasattr(RoleStatus, 'ACTIVE')
        assert hasattr(RoleStatus, 'INACTIVE')
        assert hasattr(RoleStatus, 'DEPRECATED')

    def test_member_is_instance(self):
        assert isinstance(RoleStatus.ACTIVE, RoleStatus)


class TestMFAType:
    def test_members_exist(self):
        assert hasattr(MFAType, 'TOTP')
        assert hasattr(MFAType, 'SMS')
        assert hasattr(MFAType, 'EMAIL')
        assert hasattr(MFAType, 'BACKUP_CODE')

    def test_member_is_instance(self):
        assert isinstance(MFAType.TOTP, MFAType)


class TestSessionStatus:
    def test_members_exist(self):
        assert hasattr(SessionStatus, 'ACTIVE')
        assert hasattr(SessionStatus, 'EXPIRED')
        assert hasattr(SessionStatus, 'REVOKED')
        assert hasattr(SessionStatus, 'LOGGED_OUT')

    def test_member_is_instance(self):
        assert isinstance(SessionStatus.ACTIVE, SessionStatus)


class TestUserCreateSchema:
    def test_construction_success(self):
        kwargs = {
            "username": "testuser",
            "email": "test@example.com",
            "full_name": "Test User",
            "password": "SecurePass123!",
            "must_change_password": True,
            "legal_entity_ids": [uuid4()],
            "role_ids": [uuid4()],
            "department": "IT",
            "job_title": "Developer",
            "phone_number": "08123456789",
            "is_superuser": False,
            "notes": "Test note",
        }
        instance = UserCreateSchema(**kwargs)
        assert isinstance(instance, UserCreateSchema)
        assert instance.username == kwargs["username"]


class TestUserUpdateSchema:
    def test_construction_success(self):
        kwargs = {
            "full_name": "Updated Name",
            "email": "new@example.com",
            "department": "Finance",
            "job_title": "Manager",
            "phone_number": "08123456788",
            "status": UserStatus.ACTIVE,
            "notes": "Updated notes",
            "legal_entity_ids": [uuid4()],
            "is_superuser": True,
        }
        instance = UserUpdateSchema(**kwargs)
        assert isinstance(instance, UserUpdateSchema)
        assert instance.full_name == kwargs["full_name"]


class TestUserResponseSchema:
    def test_construction_success(self):
        user_id = uuid4()
        kwargs = {
            "id": user_id,
            "username": "testuser",
            "email": "test@example.com",
            "full_name": "Test User",
            "department": "IT",
            "job_title": "Developer",
            "phone_number": "08123456789",
            "status": UserStatus.ACTIVE,
            "is_active": True,
            "is_locked": False,
            "is_superuser": False,
            "must_change_password": False,
            "mfa_enabled": False,
            "last_login_at": datetime.now(UTC),
            "last_password_change": datetime.now(UTC),
            "legal_entity_ids": [uuid4()],
            "role_ids": [uuid4()],
            "notes": "Test note",
            "created_at": datetime.now(UTC),
            "updated_at": datetime.now(UTC),
            "created_by": uuid4(),
            "created_by_name": "admin",
            "version": 1,
        }
        instance = UserResponseSchema(**kwargs)
        assert isinstance(instance, UserResponseSchema)
        assert instance.id == user_id


class TestRoleCreateSchema:
    def test_construction_success(self):
        kwargs = {
            "name": "admin",
            "description": "Administrator role",
            "parent_role_id": uuid4(),
            "is_system_role": True,
        }
        instance = RoleCreateSchema(**kwargs)
        assert isinstance(instance, RoleCreateSchema)
        assert instance.name == kwargs["name"]


class TestRoleUpdateSchema:
    def test_construction_success(self):
        kwargs = {
            "description": "Updated description",
            "status": RoleStatus.ACTIVE,
            "parent_role_id": uuid4(),
        }
        instance = RoleUpdateSchema(**kwargs)
        assert isinstance(instance, RoleUpdateSchema)
        assert instance.description == kwargs["description"]


class TestRoleResponseSchema:
    def test_construction_success(self):
        role_id = uuid4()
        kwargs = {
            "id": role_id,
            "name": "admin",
            "description": "Admin role",
            "parent_role_id": uuid4(),
            "parent_role_name": "parent",
            "is_system_role": True,
            "status": RoleStatus.ACTIVE,
            "is_active": True,
            "permission_ids": [uuid4()],
            "created_at": datetime.now(UTC),
            "updated_at": datetime.now(UTC),
            "created_by": uuid4(),
            "created_by_name": "admin",
            "version": 1,
        }
        instance = RoleResponseSchema(**kwargs)
        assert isinstance(instance, RoleResponseSchema)
        assert instance.id == role_id


class TestPermissionResponseSchema:
    def test_construction_success(self):
        perm_id = uuid4()
        kwargs = {
            "id": perm_id,
            "name": "read_users",
            "resource": "users",
            "action": "read",
            "description": "Read users",
            "is_system": True,
            "created_at": datetime.now(UTC),
        }
        instance = PermissionResponseSchema(**kwargs)
        assert isinstance(instance, PermissionResponseSchema)
        assert instance.id == perm_id


class TestUserRoleAssignSchema:
    def test_construction_success(self):
        kwargs = {"role_ids": [uuid4(), uuid4()]}
        instance = UserRoleAssignSchema(**kwargs)
        assert isinstance(instance, UserRoleAssignSchema)
        assert len(instance.role_ids) == 2


class TestRolePermissionAssignSchema:
    def test_construction_success(self):
        kwargs = {"permission_ids": [uuid4(), uuid4()]}
        instance = RolePermissionAssignSchema(**kwargs)
        assert isinstance(instance, RolePermissionAssignSchema)
        assert len(instance.permission_ids) == 2


class TestLoginRequestSchema:
    def test_construction_success(self):
        kwargs = {
            "username": "testuser",
            "password": "password123",
            "mfa_code": "123456",
            "legal_entity_id": uuid4(),
        }
        instance = LoginRequestSchema(**kwargs)
        assert isinstance(instance, LoginRequestSchema)
        assert instance.username == kwargs["username"]


class TestLoginResponseSchema:
    def test_construction_success(self):
        kwargs = {
            "access_token": "access_token_123",
            "refresh_token": "refresh_token_456",
            "token_type": "Bearer",
            "expires_in": 3600,
            "user": MagicMock(),
        }
        instance = LoginResponseSchema(**kwargs)
        assert isinstance(instance, LoginResponseSchema)
        assert instance.access_token == kwargs["access_token"]


class TestRefreshTokenRequestSchema:
    def test_construction_success(self):
        kwargs = {"refresh_token": "refresh_token_456"}
        instance = RefreshTokenRequestSchema(**kwargs)
        assert isinstance(instance, RefreshTokenRequestSchema)
        assert instance.refresh_token == kwargs["refresh_token"]


class TestChangePasswordSchema:
    def test_construction_success(self):
        kwargs = {"old_password": "old123", "new_password": "new456"}
        instance = ChangePasswordSchema(**kwargs)
        assert isinstance(instance, ChangePasswordSchema)
        assert instance.old_password == kwargs["old_password"]


class TestResetPasswordRequestSchema:
    def test_construction_success(self):
        kwargs = {"email": "test@example.com"}
        instance = ResetPasswordRequestSchema(**kwargs)
        assert isinstance(instance, ResetPasswordRequestSchema)
        assert instance.email == kwargs["email"]


class TestResetPasswordConfirmSchema:
    def test_construction_success(self):
        kwargs = {"token": "reset_token_123", "new_password": "new456"}
        instance = ResetPasswordConfirmSchema(**kwargs)
        assert isinstance(instance, ResetPasswordConfirmSchema)
        assert instance.token == kwargs["token"]


class TestForgotPasswordResponseSchema:
    def test_construction_success(self):
        kwargs = {
            "message": "Reset link sent",
            "reset_token": "token_123",
            "reset_url": "https://example.com/reset/token_123",
        }
        instance = ForgotPasswordResponseSchema(**kwargs)
        assert isinstance(instance, ForgotPasswordResponseSchema)
        assert instance.message == kwargs["message"]


class TestMFASetupResponseSchema:
    def test_construction_success(self):
        kwargs = {
            "secret_key": "SECRET123",
            "qr_code_url": "https://example.com/qr",
            "backup_codes": ["code1", "code2"],
            "issuer": "MyApp",
        }
        instance = MFASetupResponseSchema(**kwargs)
        assert isinstance(instance, MFASetupResponseSchema)
        assert instance.secret_key == kwargs["secret_key"]


class TestMFAVerifySchema:
    def test_construction_success(self):
        kwargs = {"code": "123456"}
        instance = MFAVerifySchema(**kwargs)
        assert isinstance(instance, MFAVerifySchema)
        assert instance.code == kwargs["code"]


class TestMFADisableSchema:
    def test_construction_success(self):
        kwargs = {"password": "mypassword", "mfa_code": "123456"}
        instance = MFADisableSchema(**kwargs)
        assert isinstance(instance, MFADisableSchema)
        assert instance.password == kwargs["password"]


class TestSessionResponseSchema:
    def test_construction_success(self):
        session_id = uuid4()
        kwargs = {
            "id": session_id,
            "session_token": "token_123",
            "user_id": uuid4(),
            "user_name": "testuser",
            "ip_address": "192.168.1.1",
            "user_agent": "Mozilla/5.0",
            "device_id": "device_123",
            "expires_at": datetime.now(UTC),
            "last_accessed_at": datetime.now(UTC),
            "is_active": True,
            "is_revoked": False,
            "created_at": datetime.now(UTC),
        }
        instance = SessionResponseSchema(**kwargs)
        assert isinstance(instance, SessionResponseSchema)
        assert instance.id == session_id


class TestLoginAttemptResponseSchema:
    def test_construction_success(self):
        attempt_id = uuid4()
        kwargs = {
            "id": attempt_id,
            "username": "testuser",
            "user_id": uuid4(),
            "ip_address": "192.168.1.1",
            "user_agent": "Mozilla/5.0",
            "success": True,
            "failure_reason": None,
            "attempted_at": datetime.now(UTC),
        }
        instance = LoginAttemptResponseSchema(**kwargs)
        assert isinstance(instance, LoginAttemptResponseSchema)
        assert instance.id == attempt_id


class TestUserAuditLogSchema:
    def test_construction_success(self):
        log_id = uuid4()
        kwargs = {
            "id": log_id,
            "user_id": uuid4(),
            "action": "LOGIN",
            "ip_address": "192.168.1.1",
            "user_agent": "Mozilla/5.0",
            "details": {"source": "web"},
            "created_at": datetime.now(UTC),
        }
        instance = UserAuditLogSchema(**kwargs)
        assert isinstance(instance, UserAuditLogSchema)
        assert instance.id == log_id


# ============================================================================
# MODULE-LEVEL FUNCTIONS (ROUTER ENDPOINTS)
# ============================================================================

async def test_get_iam_service_returns_service():
    request = MagicMock()
    result = await get_iam_service(request=request)
    assert result is not None


def test_ping_returns_dict():
    result = ping()
    assert isinstance(result, dict)
    # Typically returns {"status": "ok"} or similar
    assert "status" in result or "pong" in str(result)


def test_health_returns_dict():
    result = health()
    assert isinstance(result, dict)
    assert "status" in result


def test_info_returns_dict():
    result = info()
    assert isinstance(result, dict)
    # Usually contains version/name
    assert "version" in result or "name" in result


async def test_create_user_returns_user():
    service = MagicMock()
    service.create_user = MagicMock(return_value={"id": str(uuid4())})
    result = await create_user(
        request=MagicMock(),
        idempotency_key="key",
        _permission=MagicMock(),
        current_user=MagicMock(),
        legal_entity_id=uuid4(),
        service=service,
    )
    assert result is not None
    assert "id" in result


async def test_list_users_returns_list():
    service = MagicMock()
    service.list_users = MagicMock(return_value=[])
    result = await list_users(
        status=UserStatus.ACTIVE,
        is_active=True,
        search="test",
        role_id=uuid4(),
        legal_entity_id_filter=uuid4(),
        page=1,
        page_size=10,
        _permission=MagicMock(),
        service=service,
    )
    assert isinstance(result, list)


async def test_get_user_returns_user():
    service = MagicMock()
    service.get_user = MagicMock(return_value={"id": str(uuid4())})
    result = await get_user(
        user_id=uuid4(),
        _permission=MagicMock(),
        service=service,
    )
    assert result is not None
    assert "id" in result


async def test_get_user_by_username_returns_user():
    service = MagicMock()
    service.get_user_by_username = MagicMock(return_value={"id": str(uuid4())})
    result = await get_user_by_username(
        username="testuser",
        _permission=MagicMock(),
        service=service,
    )
    assert result is not None
    assert "id" in result


async def test_update_user_returns_updated():
    service = MagicMock()
    service.update_user = MagicMock(return_value={"id": str(uuid4())})
    result = await update_user(
        user_id=uuid4(),
        request=MagicMock(),
        idempotency_key="key",
        _permission=MagicMock(),
        current_user=MagicMock(),
        service=service,
    )
    assert result is not None
    assert "id" in result


async def test_deactivate_user_returns_success():
    service = MagicMock()
    service.deactivate_user = MagicMock(return_value={"success": True})
    result = await deactivate_user(
        user_id=uuid4(),
        permanent=True,
        reason="test",
        idempotency_key="key",
        _permission=MagicMock(),
        current_user=MagicMock(),
        service=service,
    )
    assert result is not None
    assert result.get("success") is True


async def test_activate_user_returns_success():
    service = MagicMock()
    service.activate_user = MagicMock(return_value={"success": True})
    result = await activate_user(
        user_id=uuid4(),
        idempotency_key="key",
        _permission=MagicMock(),
        current_user=MagicMock(),
        service=service,
    )
    assert result is not None
    assert result.get("success") is True


async def test_lock_user_returns_success():
    service = MagicMock()
    service.lock_user = MagicMock(return_value={"success": True})
    result = await lock_user(
        user_id=uuid4(),
        reason="test",
        duration_minutes=30,
        idempotency_key="key",
        _permission=MagicMock(),
        current_user=MagicMock(),
        service=service,
    )
    assert result is not None
    assert result.get("success") is True


async def test_unlock_user_returns_success():
    service = MagicMock()
    service.unlock_user = MagicMock(return_value={"success": True})
    result = await unlock_user(
        user_id=uuid4(),
        idempotency_key="key",
        _permission=MagicMock(),
        current_user=MagicMock(),
        service=service,
    )
    assert result is not None
    assert result.get("success") is True


async def test_create_role_returns_role():
    service = MagicMock()
    service.create_role = MagicMock(return_value={"id": str(uuid4())})
    result = await create_role(
        request=MagicMock(),
        idempotency_key="key",
        _permission=MagicMock(),
        current_user=MagicMock(),
        service=service,
    )
    assert result is not None
    assert "id" in result


async def test_list_roles_returns_list():
    service = MagicMock()
    service.list_roles = MagicMock(return_value=[])
    result = await list_roles(
        status=RoleStatus.ACTIVE,
        is_active=True,
        _permission=MagicMock(),
        service=service,
    )
    assert isinstance(result, list)


async def test_get_role_returns_role():
    service = MagicMock()
    service.get_role = MagicMock(return_value={"id": str(uuid4())})
    result = await get_role(
        role_id=uuid4(),
        _permission=MagicMock(),
        service=service,
    )
    assert result is not None
    assert "id" in result


async def test_update_role_returns_updated():
    service = MagicMock()
    service.update_role = MagicMock(return_value={"id": str(uuid4())})
    result = await update_role(
        role_id=uuid4(),
        request=MagicMock(),
        idempotency_key="key",
        _permission=MagicMock(),
        current_user=MagicMock(),
        service=service,
    )
    assert result is not None
    assert "id" in result


async def test_delete_role_returns_success():
    service = MagicMock()
    service.delete_role = MagicMock(return_value={"success": True})
    result = await delete_role(
        role_id=uuid4(),
        idempotency_key="key",
        _permission=MagicMock(),
        current_user=MagicMock(),
        service=service,
    )
    assert result is not None
    assert result.get("success") is True


async def test_assign_roles_to_user_returns_success():
    service = MagicMock()
    service.assign_roles_to_user = MagicMock(return_value={"success": True})
    result = await assign_roles_to_user(
        user_id=uuid4(),
        request=MagicMock(),
        idempotency_key="key",
        _permission=MagicMock(),
        current_user=MagicMock(),
        service=service,
    )
    assert result is not None
    assert result.get("success") is True


async def test_get_user_roles_returns_list():
    service = MagicMock()
    service.get_user_roles = MagicMock(return_value=[])
    result = await get_user_roles(
        user_id=uuid4(),
        _permission=MagicMock(),
        service=service,
    )
    assert isinstance(result, list)


async def test_remove_role_from_user_returns_success():
    service = MagicMock()
    service.remove_role_from_user = MagicMock(return_value={"success": True})
    result = await remove_role_from_user(
        user_id=uuid4(),
        role_id=uuid4(),
        idempotency_key="key",
        _permission=MagicMock(),
        current_user=MagicMock(),
        service=service,
    )
    assert result is not None
    assert result.get("success") is True


async def test_list_permissions_returns_list():
    service = MagicMock()
    service.list_permissions = MagicMock(return_value=[])
    result = await list_permissions(
        resource="users",
        _permission=MagicMock(),
        service=service,
    )
    assert isinstance(result, list)


async def test_assign_permissions_to_role_returns_success():
    service = MagicMock()
    service.assign_permissions_to_role = MagicMock(return_value={"success": True})
    result = await assign_permissions_to_role(
        role_id=uuid4(),
        request=MagicMock(),
        idempotency_key="key",
        _permission=MagicMock(),
        current_user=MagicMock(),
        service=service,
    )
    assert result is not None
    assert result.get("success") is True


async def test_get_role_permissions_returns_list():
    service = MagicMock()
    service.get_role_permissions = MagicMock(return_value=[])
    result = await get_role_permissions(
        role_id=uuid4(),
        _permission=MagicMock(),
        service=service,
    )
    assert isinstance(result, list)


async def test_remove_permission_from_role_returns_success():
    service = MagicMock()
    service.remove_permission_from_role = MagicMock(return_value={"success": True})
    result = await remove_permission_from_role(
        role_id=uuid4(),
        permission_id=uuid4(),
        idempotency_key="key",
        _permission=MagicMock(),
        current_user=MagicMock(),
        service=service,
    )
    assert result is not None
    assert result.get("success") is True


async def test_login_returns_login_response():
    service = MagicMock()
    service.login = MagicMock(return_value={"access_token": "token"})
    result = await login(
        request=MagicMock(),
        ip_address="192.168.1.1",
        user_agent="Mozilla/5.0",
        service=service,
    )
    assert result is not None
    assert "access_token" in result


async def test_logout_returns_success():
    service = MagicMock()
    service.logout = MagicMock(return_value={"success": True})
    result = await logout(
        current_user=MagicMock(),
        service=service,
    )
    assert result is not None
    assert result.get("success") is True


async def test_refresh_token_returns_new_token():
    service = MagicMock()
    service.refresh_token = MagicMock(return_value={"access_token": "new_token"})
    result = await refresh_token(
        request=MagicMock(),
        service=service,
    )
    assert result is not None
    assert "access_token" in result


async def test_change_password_returns_success():
    service = MagicMock()
    service.change_password = MagicMock(return_value={"success": True})
    result = await change_password(
        request=MagicMock(),
        current_user=MagicMock(),
        service=service,
    )
    assert result is not None
    assert result.get("success") is True


async def test_forgot_password_returns_response():
    service = MagicMock()
    service.forgot_password = MagicMock(return_value={"message": "Email sent"})
    result = await forgot_password(
        request=MagicMock(),
        service=service,
    )
    assert result is not None
    assert "message" in result


async def test_reset_password_returns_success():
    service = MagicMock()
    service.reset_password = MagicMock(return_value={"success": True})
    result = await reset_password(
        request=MagicMock(),
        service=service,
    )
    assert result is not None
    assert result.get("success") is True


async def test_setup_mfa_returns_mfa_setup():
    service = MagicMock()
    service.setup_mfa = MagicMock(return_value={"secret_key": "SECRET"})
    result = await setup_mfa(
        current_user=MagicMock(),
        service=service,
    )
    assert result is not None
    assert "secret_key" in result


async def test_verify_mfa_returns_success():
    service = MagicMock()
    service.verify_mfa = MagicMock(return_value={"success": True})
    result = await verify_mfa(
        request=MagicMock(),
        current_user=MagicMock(),
        service=service,
    )
    assert result is not None
    assert result.get("success") is True


async def test_disable_mfa_returns_success():
    service = MagicMock()
    service.disable_mfa = MagicMock(return_value={"success": True})
    result = await disable_mfa(
        request=MagicMock(),
        current_user=MagicMock(),
        service=service,
    )
    assert result is not None
    assert result.get("success") is True


async def test_get_user_sessions_returns_list():
    service = MagicMock()
    service.get_user_sessions = MagicMock(return_value=[])
    result = await get_user_sessions(
        current_user=MagicMock(),
        service=service,
    )
    assert isinstance(result, list)


async def test_revoke_session_returns_success():
    service = MagicMock()
    service.revoke_session = MagicMock(return_value={"success": True})
    result = await revoke_session(
        session_id=uuid4(),
        current_user=MagicMock(),
        service=service,
    )
    assert result is not None
    assert result.get("success") is True


async def test_revoke_all_other_sessions_returns_success():
    service = MagicMock()
    service.revoke_all_other_sessions = MagicMock(return_value={"success": True})
    result = await revoke_all_other_sessions(
        current_user=MagicMock(),
        service=service,
    )
    assert result is not None
    assert result.get("success") is True


async def test_get_login_attempts_returns_list():
    service = MagicMock()
    service.get_login_attempts = MagicMock(return_value=[])
    result = await get_login_attempts(
        username="testuser",
        success=True,
        start_date=datetime.now(UTC),
        end_date=datetime.now(UTC),
        page=1,
        page_size=10,
        _permission=MagicMock(),
        service=service,
    )
    assert isinstance(result, list)


async def test_get_user_audit_log_returns_list():
    service = MagicMock()
    service.get_user_audit_log = MagicMock(return_value=[])
    result = await get_user_audit_log(
        user_id=uuid4(),
        limit=10,
        _permission=MagicMock(),
        service=service,
    )
    assert isinstance(result, list)


async def test_get_user_status_returns_status():
    service = MagicMock()
    service.get_user_status = MagicMock(return_value={"status": "active"})
    result = await get_user_status(
        user_id=uuid4(),
        _permission=MagicMock(),
        service=service,
    )
    assert result is not None
    assert "status" in result


async def test_get_user_history_returns_list():
    service = MagicMock()
    service.get_user_history = MagicMock(return_value=[])
    result = await get_user_history(
        user_id=uuid4(),
        _permission=MagicMock(),
        service=service,
    )
    assert isinstance(result, list)